

audioRootDir = "D:\Git\qpzm_mfa_dae\src\dataset\audio_Healthy";
audioPath = fullfile(audioRootDir, "121_1b1_Tc_sc_Meditron.wav");

[y, sr] = audioread(audioPath);

stft(y,sr,...
'Window',hamming(2048,'symmetric'),...
'OverlapLength', 128,...
'FrequencyRange', 'onesided',...
'FFTLength',2048);